### ISSUE TITLE
Popeye terminating with OOMKilled error

### ISSUE THREAD

**Issue by adonaicosta** [undistro/zora#190]
## Description
sometimes the scan pod has outfomemory 

## Expected Behavior
Pod state Completed

**Comment by matheusfm** [comment]
Thanks for reporting this issue.

It happens because the default resource limits is not enough for your target cluster.

For now you can edit the `popeye` plugin (`kubectl edit plugin popeye -n zora-system`) to increase the limit.

**Comment by matheusfm** [comment]
TODO: popeye resources as helm chart parameters. 
Example: https://github.com/undistro/zora/blob/main/charts/zora/values.yaml#L89
