### ISSUE TITLE
Build is pulling in invalid go version from sigs.k8s.io/controller-runtime/tools/setup-envtest

### ISSUE THREAD

**Issue by knrc** [undistro/zora#253]
## Description
Build failures, see [failing build](https://github.com/undistro/zora/actions/runs/8391233903)

## Expected Behavior
A cllean build

## System Information
 - GitHub Actions

**Comment by matheusfm** [comment]
It's always downloading the latest version of `setup-envtest`. I'll take a look

**Comment by knrc** [comment]
> It's always downloading the latest version of `setup-envtest`. I'll take a look

Already fixed, PR submitted.

And we shouldn't be using latest :)
